import express from "express"
import { sendConnection, acceptConnection, rejectConnection, getConnectionStatus, removeConnection, getConnectionRequests, getUserConnections }
 from "../controllers/connection.controllers.js"
import { verifyJWT } from "../middleware/auth.middleware.js"

const connectionRouter=express.Router()

connectionRouter.route("/send/:id").post(verifyJWT, sendConnection) //id= id of the person to which we are sending request
connectionRouter.route("/accept/:connectionId").put(verifyJWT,acceptConnection)//id= id of the connection request generated by DB
connectionRouter.route("/reject/:connectionId").put(verifyJWT,rejectConnection)
connectionRouter.route("/getconnectionstatus/:id").get(verifyJWT,getConnectionStatus)
connectionRouter.route("/removeconnection/:id").delete(verifyJWT,removeConnection)
connectionRouter.route("/requests").get(verifyJWT,getConnectionRequests)
connectionRouter.route("/").get(verifyJWT,getUserConnections)


export default connectionRouter